"""Initial migration

Revision ID: 735d2a0c9d19
Revises: 
Create Date: 2024-04-22 17:22:40.364256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '735d2a0c9d19'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(engine_name: str) -> None:
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    globals()["downgrade_%s" % engine_name]()





def upgrade_QAAS_DB() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    print("called upgrade")
    pass
    # ### end Alembic commands ###


def downgrade_QAAS_DB() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

